apiVersion: apps/v1
kind: Deployment
metadata: 
  name: hpa-deployment
  namespace: test-namespace
  labels:
    name: hpa-label
spec:
  replicas: 2
  selector:
    matchLabels:
      name: hpa-label
  template:
    metadata:
      name: hpa-pod
      labels:
        name: hpa-label
    spec:
      containers:
        - name: hpa-container
          image: k8s.gcr.io/hpa-example
          ports:
           - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "150m"
              memory: "256Mi"

---

apiVersion: v1
kind: Service
metadata: 
  name: hpa-service
  namespace: test-namespace
spec:
  type: NodePort
  ports:
   - port: 8080
     targetPort: 8080
  selector:
    name: hpa-label
    
---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
  name: hpa-horizontalpodautoscaler
  namespace: test-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hpa-deployment
  minReplicas: 2 
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization : 40
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 40
          
    