apiVersion: v1 
kind: Pod 
metadata: 
  name: nginx-liveness
  namespace: test-namespace
spec: 
  containers: 
  - name: liveness 
    image: nginx 
    ports: 
        - containerPort: 80 
    livenessProbe: 
      tcpSocket:
        port: 80
      initialDelaySeconds: 2 #Default 0 
      periodSeconds: 2
    readinessProbe:
      tcpSocket:
        port: 80
