apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: test-namespace
spec:
  containers:
    - name: nginx-test-container
      image: nginx
      ports:
        - containerPort: 8080
      resources:
        requests:
          cpu: 200m
          memory: 200Mi
        limits:
          cpu: 500m
          memory: 500Mi
    
