apiVersion: v1
kind: Pod
metadata:
  name: mavenapp-pod1
  labels:
    app: maven-app
    kindof: web-application
  namespace: test-namespace
spec:
  containers:
    - name: mavenapp-container1
      image: dockerhandson/maven-web-application:1
      ports:
        - containerPort: 8080
      resources:
        requests:
          cpu: 200m
          memory: 100Mi
        limits:
          cpu: 500m
          memory: 400Mi
