apiVersion: v1
kind: Pod
metadata:
  name: mavenapp-pod
  labels:
    work: creatingcontainer
    location: pune
    app: maven-app
  namespace: test-namespace
spec:
  containers:
    - name: mavenapp-container
      image: dockerhandson/maven-web-application:1
      ports:
        - containerPort: 8080
      env:
        - name: USER_NAME
          value: USER_RAJA
      resources:
        requests:
          cpu: 200m
          memory: 200Mi
        limits:
          cpu: 500m
          memory: 512Mi
        
      