apiVersion: v1
kind: ReplicationController
metadata:
  name: test-replication-controller
  namespace: test-namespace
spec:
  replicas: 2
  selector:
    app: maven-nginx-app
  template:
    metadata:
      name: replication-controller-pod
      labels: 
        app: maven-nginx-app
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
        - name: maven-app
          image: dockerhandson/maven-web-application:1
          ports:
            - containerPort: 8080
  
 