apiVersion: v1
kind: ReplicationController
metadata:
  name: test-rc
  namespace: test-namespace
  labels:
    app: java-rc-label
spec:
  replicas: 2
  selector:
    app: java-web-app-label
  template:
    metadata:
      name: java-web-app-pods
      labels:
        app: java-web-app-label
    spec:
      containers:
        - name: java-rc-container
          image: dockerhandson/java-web-application:1
          ports:
            - containerPort: 8080
          
---

apiVersion: v1
kind: Service
metadata:
  name: java-rc-service
  namespace: test-namespace
spec:
  type: NodePort
  selector:
    app: java-rc-label
  ports:
    - port: 8080
      targetPort: 80
