apiVersion: v1
kind: ReplicationController
metadata:
  name: python-app-rc
  namespace: test-namespace
spec:
  replicas: 2
  template:
    metadata:
      name: python-app-pod
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app-container
          image: dockerhandson/python-flask-app:1
          ports:
            - containerPort: 8080
        
---

apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  namespace: test-namespace
spec:
  selector:
    app: python-app
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
          