apiVersion: v1
kind: Pod
metadata:
  name: java-nginx-pod
  namespace: test-namespace
  labels:
    app: java-nginx-label
spec:
  containers:
    - name: javacontainer
      image: dockerhandson/java-web-application:1
      ports:
        - containerPort: 8080
    - name: nginxcontainer
      image: nginx
      ports:
        - containerPort: 80
        
---
apiVersion: v1
kind: Service
metadata:
  name: java-nginx-svc
  namespace: test-namespace
spec:
  type: NodePort
  selector:
    app: java-nginx-label
  ports:
    - name: java-port
      port: 8080
      targetPort: 8080
    - name: nginx-port
      port: 80
      targetPort: 80