apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-mongo-app
  namespace: test-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-mongo-app-label
  template:
    metadata:
      name: spring-mongo-app-pod
      labels: 
        app: spring-mongo-app-label
    spec:
      containers:
        - name: spring-mongo-app-container
          image: dockerhandson/spring-boot-mongo
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "150m"
              memory: "150Mi"
          env:
            - name: MONGO_DB_HOSTNAME
              value: mongo-svc
            - name: MONGO_DB_USERNAME
              value: mongoadmin
            - name: MONGO_DB_PASSWORD
              value: mongopass

---

apiVersion: v1
kind: Service
metadata:
  name: spring-app-svc
  namespace: test-namespace
spec:
  type: NodePort
  selector:
    app: spring-mongo-app-label
  ports:
    - port: 8080
      targetPort: 8080
      
---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongo-rs
  namespace: test-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-label
  template:
    metadata:
      name: mongo-pod
      labels:
        app: mongo-label
    spec:
      containers:
        - name: mongo-container
          image: mongo
          ports:
            - containerPort: 27017
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "150m"
              memory: "150Mi"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: mongoadmin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mongopass
          volumeMounts:
            - name: mongo-vol
              mountPath: /data/db
      volumes:
        - name: mongo-vol
          hostPath:
            path: /tmp/mongo
               
---

apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: test-namespace
spec:
  type: ClusterIP
  selector:
    app: mongo-label
  ports:
    - port: 27017
      targetPort: 27017
      
      
